import AvatarI from '../../img/avatar.png';
import delivery from '../../img/delivery.png';
import HeroBgI from '../../img/hero-bg.png';
import ChickenI from "../../img/c3.png";
import FishI from "../../img/fi3.png";
import IcreamI from "../../img/i1.png";
import StrawberryI from "../../img/f5.png";
import NotFoundI from "../../img/NotFound.svg";
import Momo from '../../img/momo.png';
import Visa  from '../../img/visa.png';
import EmptyCartI from '../../img/emptyCart.svg';

export const Avatar = AvatarI;
export const bikeDelivery = delivery;
export const HeroBg = HeroBgI;
export const Chicken = ChickenI;
export const Fish = FishI;
export const Icream = IcreamI;
export const Strawberry = StrawberryI;
export const NotFoundImg = NotFoundI;
export const MOMO = Momo;
export const CreaditCard = Visa;
export const EmptyCartImg = EmptyCartI;